### ISSUE TITLE
Bug in MP3.pm POD

### ISSUE THREAD

**Issue by deepakg** [riemann42/Music-Tag-MP3#1]
Under synopsis, a method $info->get_info() is mentioned. It doesn't exist in MP3.pm. You meant $info->get_tag(); perhaps?

=head1 SYNOPSIS

```
use Music::Tag

my $info = Music::Tag->new($filename, { quiet => 1 }, "MP3");
#$info->get_info();
    $info->get_tag();

print "Artist is ", $info->artist;
```

**Comment by riemann42** [comment]
Yes.  Will be corrected soon.  Thanks!

**Comment by riemann42** [comment]
Corrected.
